"""Transform tests on a saved fixture - no network, no credentials.

The fixture (tests/fixtures/sample_cache.json) is generated by
tools/make_sample_fixture.py; tools/anonymise_cache.py can produce one from a
real tenant cache.
"""
import json
import socket
from pathlib import Path

import pandas as pd
import pytest

from src import report, transform
from src.config import ALLOWED_SCOPES, ConfigError, validate_scopes

FIXTURE = Path(__file__).parent / "fixtures" / "sample_cache.json"
USAGE = ["feature_utilization"]


@pytest.fixture(autouse=True)
def no_network(monkeypatch):
    def guard(*a, **k):
        raise RuntimeError("tests must not touch the network")
    monkeypatch.setattr(socket, "create_connection", guard)
    monkeypatch.setattr(socket.socket, "connect", guard)


@pytest.fixture(scope="module")
def cache():
    return json.loads(FIXTURE.read_text())


@pytest.fixture(scope="module")
def events(cache):
    return transform.flatten(cache["activities"])


@pytest.fixture(scope="module")
def summary(events, cache):
    return transform.build_user_summary(events, cache["users"], usage_event_names=USAGE)


def test_fixture_is_big_enough(events):
    usage = transform.usage_events(events, USAGE)
    assert len(usage) >= 50
    assert usage["app"].nunique() >= 5


def test_flatten_columns_and_one_row_per_event(cache, events):
    assert list(events.columns[:9]) == transform.RAW_COLUMNS
    n_events = sum(len(a["events"]) for a in cache["activities"])
    assert len(events) == n_events
    assert str(events["timestamp"].dt.tz) == "UTC"
    assert (events["user_email"] == events["user_email"].str.lower()).all()
    assert events["ip"].str.startswith("203.0.113.").all()


def test_app_normalisation(events):
    assert set(events["app"]) <= set(transform.APP_COLUMNS)
    assert "GMAIL" not in set(events["app"])
    assert transform.normalise_app("GMAIL") == "gmail"
    assert transform.normalise_app("Google Docs") == "docs"
    assert transform.normalise_app("dynamite") == "chat"
    assert transform.normalise_app("bard") == "gemini_app"
    assert transform.normalise_app("calendar") == "calendar"
    assert transform.normalise_app("workflows") == "workflows"
    assert transform.normalise_app("some_new_app") == "other"
    assert transform.normalise_app(None) == "other"


def test_unknown_parameters_are_reported_and_kept(cache, events):
    rep = transform.parameter_report(cache["activities"])
    assert rep["unknown_parameters"] == ["surface_id", "tags"]
    assert "some_new_app" in rep["unmapped_app_values"]
    assert rep["event_names"]["feature_feedback"] == 1
    row = events[events["other_params"].str.contains("surface_id")].iloc[0]
    assert json.loads(row["other_params"]) == {"event_category": "generative_ai",
                                              "surface_id": "compose", "tags": "a|b"}


def test_param_map_override(cache):
    ev = transform.flatten(cache["activities"], {"feature": ["action"]})
    assert set(ev["feature"]) <= {"generate", "summarize", "refine", "ask", "insert"}


def test_every_directory_user_appears(summary, cache):
    active_dir = {u["primaryEmail"] for u in cache["users"] if not u["suspended"]}
    assert active_dir <= set(summary["user_email"])
    assert list(summary.columns) == transform.USER_COLUMNS


def test_zero_usage_users(summary):
    zero = summary[summary["total_actions"] == 0]
    assert set(zero["user_email"]) == {"user6@example.com", "user7@example.com", "user8@example.com"}
    assert (zero["tier"] == "Zero").all()
    assert zero["first_used"].isna().all() and zero["last_used"].isna().all()
    assert (zero["active_days"] == 0).all()


def test_totals_and_tiers(summary):
    s = summary.set_index("user_email")
    assert s.loc["user1@example.com", "total_actions"] == 31   # 30 + second event in one activity
    assert s.loc["user2@example.com", "total_actions"] == 13
    assert s.loc["user4@example.com", "total_actions"] == 5
    assert s.loc["user1@example.com", "tier"] == "High"
    assert s.loc["user2@example.com", "tier"] == "Medium"
    assert s.loc["user4@example.com", "tier"] == "Medium"
    assert s.loc["user5@example.com", "tier"] == "Low"
    assert s.loc["user4@example.com", "other"] == 1
    # Per-app columns add up to the total.
    assert (summary[transform.APP_COLUMNS].sum(axis=1) == summary["total_actions"]).all()
    assert summary["total_actions"].sum() == 58
    assert summary["user_email"].iloc[0] == "user1@example.com"   # sorted by actions


@pytest.mark.parametrize("total,tier", [(0, "Zero"), (1, "Low"), (4, "Low"), (5, "Medium"),
                                        (19, "Medium"), (20, "High"), (500, "High")])
def test_tier_boundaries(total, tier):
    assert transform.tier_for(total) == tier


def test_non_usage_events_excluded(events, cache):
    with_all = transform.build_user_summary(events, cache["users"], usage_event_names=[])
    assert with_all.set_index("user_email").loc["user1@example.com", "total_actions"] == 32


def test_user_not_in_directory_kept(summary):
    row = summary.set_index("user_email").loc["user11@example.com"]
    assert row["ou_path"] == "(not in directory)"
    assert row["total_actions"] == 2


def test_suspended_users(events, cache, summary):
    assert "user9@example.com" not in set(summary["user_email"])
    incl = transform.build_user_summary(events, cache["users"], usage_event_names=USAGE,
                                        include_suspended=True)
    s = incl.set_index("user_email")
    assert s.loc["user9@example.com", "total_actions"] == 3
    assert bool(s.loc["user10@example.com", "suspended"]) is True
    assert len(incl) == len(summary) + 2


def test_ou_filter(events, cache):
    s = transform.build_user_summary(events, cache["users"], usage_event_names=USAGE,
                                     ou_filter=["/Sales"])
    # Sub-OUs are included; suspended and not-in-directory users are not.
    assert set(s["user_email"]) == {"user1@example.com", "user2@example.com",
                                    "user3@example.com", "user7@example.com"}
    s = transform.build_user_summary(events, cache["users"], usage_event_names=USAGE,
                                     ou_filter=["/Sales/APAC"])
    assert set(s["user_email"]) == {"user3@example.com", "user7@example.com"}
    # "/Sal" must not match "/Sales".
    s = transform.build_user_summary(events, cache["users"], usage_event_names=USAGE,
                                     ou_filter=["/Sal"])
    assert s.empty


def test_active_days_and_timezone(events, cache):
    utc = transform.build_user_summary(events, cache["users"], usage_event_names=USAGE)
    sgt = transform.build_user_summary(events, cache["users"], usage_event_names=USAGE,
                                       tz="Asia/Singapore")
    u = utc.set_index("user_email")
    assert 1 <= u.loc["user1@example.com", "active_days"] <= 28
    assert u.loc["user5@example.com", "active_days"] == 1
    assert (sgt["total_actions"].values == utc["total_actions"].values).all()
    assert (u["last_used"].dropna() >= u["first_used"].dropna()).all()


def test_org_summary(summary, events, cache):
    scoped = transform.scoped_events(events, summary, USAGE)
    org = transform.build_org_summary(summary, scoped, start_time=cache["start_time"],
                                      end_time=cache["end_time"], window_days=28)
    m = dict(zip(org["metric"], org["value"]))
    assert m["total_users"] == 9
    assert m["active_users"] == 6
    assert m["adoption_pct"] == round(100 * 6 / 9, 1)
    assert m["total_actions"] == 58
    assert sum(m[f"actions_{a}"] for a in transform.APP_COLUMNS) == 58
    assert m["users_tier_zero"] == 3 and m["users_tier_high"] == 1
    assert "top_feature_1" in m and "top_feature_11" not in m
    assert m["adoption_pct_ou:/Engineering"] == "66.7 (2/3)"
    assert scoped["user_email"].isin(summary["user_email"]).all()


def test_compare(summary, events, cache):
    scoped = transform.scoped_events(events, summary, USAGE)
    org = transform.build_org_summary(summary, scoped, start_time=cache["start_time"],
                                      end_time=cache["end_time"], window_days=28)
    prev = org.copy()
    prev.loc[prev["metric"] == "active_users", "value"] = 4
    diff = transform.compare_org_summaries(prev, org).set_index("metric")
    assert diff.loc["active_users", "change"] == 2
    assert diff.loc["total_actions", "change"] == 0


def test_empty_input():
    ev = transform.flatten([])
    users = [{"primaryEmail": "a@example.com", "name": {"fullName": "A"}, "orgUnitPath": "/"}]
    s = transform.build_user_summary(ev, users, usage_event_names=USAGE)
    assert len(s) == 1 and s.iloc[0]["tier"] == "Zero"
    org = transform.build_org_summary(s, ev, start_time="x", end_time="y", window_days=28)
    assert dict(zip(org["metric"], org["value"]))["active_users"] == 0


def test_outputs_written(tmp_path, summary, events, cache):
    scoped = transform.scoped_events(events, summary, USAGE)
    org = transform.build_org_summary(summary, scoped, start_time=cache["start_time"],
                                      end_time=cache["end_time"], window_days=28)
    paths = report.write_csvs(tmp_path, "2026-09-25", events, summary, org)
    raw = pd.read_csv(paths["raw_events"])
    assert list(raw.columns) == transform.RAW_COLUMNS
    us = pd.read_csv(paths["user_summary"])
    assert list(us.columns) == transform.USER_COLUMNS
    dash = report.render_dashboard(tmp_path, "2026-09-25",
                                   report.dashboard_context(summary, scoped, org))
    html = dash.read_text()
    assert "user1@example.com" in html and "user6@example.com" in html
    assert "203.0.113." not in html            # IPs never reach the dashboard
    assert "<script" not in html and "http://" not in html  # self-contained, no external calls
    assert (tmp_path / "dashboard_2026-09-25.html").exists()


def test_scope_guard():
    assert validate_scopes(list(ALLOWED_SCOPES)) == list(ALLOWED_SCOPES)
    with pytest.raises(ConfigError):
        validate_scopes(list(ALLOWED_SCOPES) + ["https://www.googleapis.com/auth/admin.directory.user"])
    with pytest.raises(ConfigError):
        validate_scopes(ALLOWED_SCOPES[:1])
